"""add datasync to table

Revision ID: 095dbff55397
Revises: d8e8c4e20027
Create Date: 2024-09-11 23:32:41.075005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095dbff55397'
down_revision = 'd8e8c4e20027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('database_datasync_id_fkey', 'database', type_='foreignkey')
    op.drop_column('database', 'datasync_id')
    op.add_column('datasync', sa.Column('es_index', sa.String(), nullable=True))
    op.add_column('table', sa.Column('datasync_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'table', 'datasync', ['datasync_id'], ['id'])
    op.drop_column('table', 'es_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('es_index', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.drop_column('table', 'datasync_id')
    op.drop_column('datasync', 'es_index')
    op.add_column('database', sa.Column('datasync_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('database_datasync_id_fkey', 'database', 'datasync', ['datasync_id'], ['id'])
    # ### end Alembic commands ###
