"""add es_columns to table

Revision ID: 159293a884d3
Revises: 095dbff55397
Create Date: 2024-09-16 16:42:09.891389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159293a884d3'
down_revision = '095dbff55397'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('es_columns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'es_columns')
    # ### end Alembic commands ###
