"""re-initialize migrations

Revision ID: 214795b15e30
Revises: 
Create Date: 2024-09-10 03:18:05.192571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214795b15e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('db_user', sa.String(), nullable=True),
    sa.Column('db_name', sa.String(), nullable=True),
    sa.Column('db_password', sa.String(), nullable=True),
    sa.Column('db_host', sa.String(), nullable=True),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('db_table', sa.String(), nullable=True),
    sa.Column('db_schema', sa.JSON(), nullable=True),
    sa.Column('es_index', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasync',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database',
    sa.Column('postgres_url', sa.String(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('datasync_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['datasync_id'], ['datasync.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('columns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('es_index', sa.String(), nullable=True),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['database.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    op.drop_table('database')
    op.drop_table('datasync')
    op.drop_table('user')
    op.drop_table('setting')
    # ### end Alembic commands ###
