"""add relationships to table data

Revision ID: d8e8c4e20027
Revises: e80bc40e71a0
Create Date: 2024-09-11 18:28:35.030529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e8c4e20027'
down_revision = 'e80bc40e71a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasync', sa.Column('schema', sa.JSON(), nullable=True))
    op.add_column('table', sa.Column('relationships', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'relationships')
    op.drop_column('datasync', 'schema')
    # ### end Alembic commands ###
